server:
  port: 8800

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: jwt, oauth2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33060/umbrella?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 2982
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    show-sql: true


cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      bucket:
    region:
      static: ap-northeast-2
    stack:
      auto: false


servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 30MB


logging:
  level:
    org.hibernate.type: trace


